const mongoose = require("mongoose");

const adminSettingSchema = new mongoose.Schema(
  {
    siteName: { type: String, default: "CouponX" },
    siteTagline: { type: String, default: "Save More, Shop More!" },
    siteUrl: { type: String, default: "https://www.couponx.com" },
    adminEmail: { type: String, default: "superadmin@couponx.com" },
    businessName: { type: String, default: "CouponX Private Limited" },
    businessEmail: { type: String, default: "support@couponx.com" },
    businessPhone: { type: String, default: "+91 98765 43210" },
    businessAddress: { type: String, default: "123, Business Street, Sector 62, Noida, Uttar Pradesh - 201301, India" },
    supportEmail: { type: String, default: "help@couponx.com" },
    supportPhone: { type: String, default: "+91 98765 00000" },
    emailProvider: { type: String, default: "smtp" },
    smtpHost: { type: String, default: "smtp.gmail.com" },
    smtpPort: { type: Number, default: 587 },
    smtpUsername: { type: String, default: "" },
    smtpPassword: { type: String, default: "" },
    smtpFromName: { type: String, default: "CouponX" },
    smtpFromEmail: { type: String, default: "noreply@couponx.com" },
    enableEmailNotifications: { type: Boolean, default: true },
    enableOrderEmails: { type: Boolean, default: true },
    enableMarketingEmails: { type: Boolean, default: false },
    paymentGateway: { type: String, default: "razorpay" },
    currencyCode: { type: String, default: "INR" },
    razorpayKeyId: { type: String, default: "" },
    razorpayKeySecret: { type: String, default: "" },
    taxPercent: { type: Number, default: 18 },
    minimumWithdrawalAmount: { type: Number, default: 100 },
    autoReleasePayouts: { type: Boolean, default: false },
    commissionPercent: { type: Number, default: 10 },
    minimumTrustScore: { type: Number, default: 60 },
    aiMatchThreshold: { type: Number, default: 90 },
    maxFreeListings: { type: Number, default: 10 },
    withdrawalFee: { type: Number, default: 2 },
    allowRegistration: { type: Boolean, default: true },
    enableRecaptcha: { type: Boolean, default: true },
    requireEmailVerification: { type: Boolean, default: true },
    passwordMinLength: { type: Number, default: 8 },
    maxLoginAttempts: { type: Number, default: 5 },
    sessionTimeoutMinutes: { type: Number, default: 120 },
    adminNewUserAlerts: { type: Boolean, default: true },
    adminCouponAlerts: { type: Boolean, default: true },
    adminDisputeAlerts: { type: Boolean, default: true },
    adminWithdrawalAlerts: { type: Boolean, default: true },
    sendPushNotifications: { type: Boolean, default: false },
    sendEmailSummaries: { type: Boolean, default: true },
    summaryFrequency: { type: String, default: "daily" }
  },
  { timestamps: true }
);

module.exports = mongoose.model("AdminSetting", adminSettingSchema);
